//
//  scale.swift
//  AudioKit For iOS
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright © 2015 AudioKit. All rights reserved.
//

import Foundation

extension AKOperation {
    
    /** scale: Linear tranformation from one range to another, based on minimum and maximum values. - This module scales from -1 to 1 to a range defined by a minimum and maximum
     point in the input and output domain.
     - Parameter minimum: Minimum value to scale to. (Default: 0.0, Minimum: -1000000.0, Maximum: 1000000.0)
     - Parameter maximum: Maximum value to scale to. (Default: 1.0, Minimum: -1000000.0, Maximum: 1000000.0)
     */
    public mutating func scale(
        minimum minimum: AKOperation = 0.0.ak,
        maximum: AKOperation = 1.0.ak) {
            self = self.scaledTo(minimum: minimum, maximum: maximum)
    }
    
    /** scale: Linear tranformation from one range to another, based on minimum and maximum values. - This module scales from -1 to 1 to a range defined by a minimum and maximum
     point in the input and output domain.
     - returns: AKOperation
     - Parameter minimum: Minimum value to scale to. (Default: 0.0, Minimum: -1000000.0, Maximum: 1000000.0)
     - Parameter maximum: Maximum value to scale to. (Default: 1.0, Minimum: -1000000.0, Maximum: 1000000.0)
     */
    public func scaledTo(
        minimum minimum: AKOperation = 0.0.ak,
        maximum: AKOperation = 1.0.ak
        ) -> AKOperation {
            return AKOperation("\(self)\(minimum)\(maximum)biscale")
    }
    /** scale: Linear tranformation from one range to another, based on minimum and maximum values. - This module scales from -1 to 1 to a range defined by a minimum and maximum
     point in the input and output domain.
     - returns: AKOperation
     - Parameter minimum: Minimum value to scale to. (Default: 0.0, Minimum: -1000000.0, Maximum: 1000000.0)
     - Parameter maximum: Maximum value to scale to. (Default: 1.0, Minimum: -1000000.0, Maximum: 1000000.0)
     */
    public func scaledTo(
        minimum minimum: Double = 0.0,
        maximum: Double = 1.0
        ) -> AKOperation {
            return  self.scaledTo(minimum: minimum.ak, maximum: maximum.ak)
    }
}

/** scale: Linear tranformation from one range to another, based on minimum and maximum values. - This module scales from -1 to 1 to a range defined by a minimum and maximum
 point in the input and output domain.
 - returns: AKOperation
 - Parameter input: Input signal.
 - Parameter minimum: Minimum value to scale to. (Default: 0.0, Minimum: -1000000.0, Maximum: 1000000.0)
 - Parameter maximum: Maximum value to scale to. (Default: 1.0, Minimum: -1000000.0, Maximum: 1000000.0)
 */
public func scale(
    input: AKOperation,
    minimum: AKOperation = 0.0.ak,
    maximum: AKOperation = 1.0.ak
    ) -> AKOperation {
        return input.scaledTo(minimum: minimum, maximum: maximum)
}