//
//  randomVertexPulse.swift
//  AudioKit For iOS
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright © 2015 AudioKit. All rights reserved.
//

import Foundation

extension AKOperation {

    /** randomVertexPulse: Line segments between random values within a range - Line segments between random values within a range
     - returns: AKOperation
     - Parameter minimum: Minimum value (Default: 0)
     - Parameter maximum: Maximum value (Default: 1)
     - Parameter updateFrequency: Frequency to change values. (Default: 3)
     */
    public static func randomVertexPulse(
        minimum minimum: AKOperation = 0.ak,
        maximum: AKOperation = 1.ak,
        updateFrequency: AKOperation = 3.ak
        ) -> AKOperation {
            return AKOperation("\(minimum)\(maximum)\(updateFrequency)randi")
    }
}

/** randomVertexPulse: Line segments between random values within a range - Line segments between random values within a range
- returns: AKOperation
- Parameter minimum: Minimum value (Default: 0)
- Parameter maximum: Maximum value (Default: 1)
- Parameter updateFrequency: Frequency to change values. (Default: 3)
*/
public func randomVertexPulse(
    minimum minimum: AKOperation = 0.ak,
    maximum: AKOperation = 1.ak,
    updateFrequency: AKOperation = 3.ak
    ) -> AKOperation {
        return AKOperation.randomVertexPulse(minimum: minimum, maximum: maximum, updateFrequency: updateFrequency)
}