//
//  AKFormantFilterAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

#ifndef AKFormantFilterAudioUnit_h
#define AKFormantFilterAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKFormantFilterAudioUnit : AUAudioUnit
@end

#endif /* AKFormantFilterAudioUnit_h */
