//
//  AKDCBlockAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2016 Aurelius Prochazka. All rights reserved.
//

#ifndef AKDCBlockAudioUnit_h
#define AKDCBlockAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKDCBlockAudioUnit : AUAudioUnit
- (void)start;
- (void)stop;
- (BOOL)isPlaying;
@end

#endif /* AKDCBlockAudioUnit_h */
