//
//  AKDecimator.swift
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

import AVFoundation

public class AKDecimator: AKOperation {

    var internalAU: AKDecimatorAudioUnit?
    var token: AUParameterObserverToken?

    var bitDepthParameter:   AUParameter?
    var sampleRateParameter: AUParameter?

    public var bitDepth: Float = 8 {
        didSet {
            bitDepthParameter?.setValue(bitDepth, originator: token!)
        }
    }
    public var sampleRate: Float = 10000 {
        didSet {
            sampleRateParameter?.setValue(sampleRate, originator: token!)
        }
    }

    public init(_ input: AKOperation) {
        super.init()

        var description = AudioComponentDescription()
        description.componentType         = kAudioUnitType_Effect
        description.componentSubType      = 0x64636d38 /*'dcm8'*/
        description.componentManufacturer = 0x41754b74 /*'AuKt'*/
        description.componentFlags        = 0
        description.componentFlagsMask    = 0

        AUAudioUnit.registerSubclass(
            AKDecimatorAudioUnit.self,
            asComponentDescription: description,
            name: "Local AKDecimator",
            version: UInt32.max)

        AVAudioUnit.instantiateWithComponentDescription(description, options: []) {
            avAudioUnit, error in

            guard let avAudioUnitEffect = avAudioUnit else { return }

            self.output = avAudioUnitEffect
            self.internalAU = avAudioUnitEffect.AUAudioUnit as? AKDecimatorAudioUnit
            AKManager.sharedInstance.engine.attachNode(self.output!)
            AKManager.sharedInstance.engine.connect(input.output!, to: self.output!, format: nil)
        }

        guard let tree = internalAU?.parameterTree else { return }

        bitDepthParameter   = tree.valueForKey("bitDepth")   as? AUParameter
        sampleRateParameter = tree.valueForKey("sampleRate") as? AUParameter

        token = tree.tokenByAddingParameterObserver {
            address, value in

            dispatch_async(dispatch_get_main_queue()) {
                if address == self.bitDepthParameter!.address {
                    self.bitDepth = value
                }
                else if address == self.sampleRateParameter!.address {
                    self.sampleRate = value
                }
            }
        }

    }
}
