module: AudioKit
author: Aurelius Prochazka
author_url: http://audiokit.io/
github_url: https://github.com/AudioKit/AudioKit
min_acl: public
readme: ../README.md
#swift_version: 3.0


custom_categories:
  - name: Internals
    children:
    - AudioEngine
    - AudioUnitBase
    - AudioUnitContainer
    - AudioUnitPropertyListener
    - AutomationCurve
    - CallbackInstrument
    - Device
    - DeviceID
    - NodeParameter
    - NodeParameterDef
    - NodeParameterType
    - NodeRecorder
    - ParameterAutomationPoint
    - Settings
    - Table
    - TableType

  - name: MIDI
    children:
    - AppleMIDIEvent
    - BluetoothMIDIButton
    - CMIDICallback
    - EndpointInfo
    - MIDI
    - MIDIBeatObserver
    - MIDIByte
    - MIDICallback
    - MIDICallbackInstrument
    - MIDIChannel
    - MIDIClockListener
    - MIDIControl
    - MIDICustomMetaEvent
    - MIDICustomMetaEventType
    - MIDIEvent
    - MIDIFile
    - MIDIFileChunk
    - MIDIFileChunkEvent
    - MIDIFileChunkType
    - MIDIFileTempoTrack
    - MIDIFileTrack
    - MIDIFileTrackChunk
    - MIDIFileTrackNoteMap
    - MIDIHelper
    - MIDIInstrument
    - MIDIListener
    - MIDIMessage
    - MIDIMonoPolyListener
    - MIDINode
    - MIDINoteData
    - MIDINoteDuration
    - MIDINoteNumber
    - MIDIOMNIListener
    - MIDIPacket
    - MIDIPacketList
    - MIDIPlayer
    - MIDIProgramChangeEvent
    - MIDISampler
    - MIDIStatus
    - MIDIStatusType
    - MIDISysExMessage
    - MIDISystemCommand
    - MIDISystemCommandType
    - MIDISystemRealTimeListener
    - MIDISystemRealTimeObserver
    - MIDITempoListener
    - MIDITempoObserver
    - MIDITransformer
    - MIDITimeFormat
    - MIDITimeout
    - MIDITrackView
    - MIDIVariableLengthQuantity
    - MIDIVelocity
    - MIDIWord
    - ObserverProtocol

  - name: Sequencing
    children:
    - AppleSequencer
    - Duration
    - MusicTrackManager
    - NoteEventSequence
    - Sequencer
    - SequenceEvent
    - SequenceNote
    - SequencerTrack

  - name: Tuning
    children:
    - TuningTable
    - TuningTableBase
    - TuningTableDelta12ET
    - TuningTableETNN

  - name: Utilities
    children:
    - audition(_:)
    - CheckError(_:)
    - CVoidCallback
    - ExceptionCatcher(_:)
    - FormatConverter
    - fourCC(_:)
    - Log(_:log:type:file:function:line:)
    - Occupiable
    - OSLog
    - OSStatus
    - SampleIndex


  - name: Nodes
    children:
    - Node
    - Polyphonic
    - PolyphonicNode
    - Toggleable
    - OperationGenerator

  - name: Delay Nodes
    children:
    - Delay
    - StereoDelay
    - VariableDelay

  - name: Distortion Nodes
    children:
    - BitCrusher
    - Clipper
    - Decimator
    - DiodeClipper
    - Distortion
    - RingModulator
    - TanhDistortion

  - name: Dynamics Nodes
    children:
    - Compressor
    - DynamicsProcessor
    - DynamicRangeCompressor
    - DynaRageCompressor
    - Expander
    - PeakLimiter

  - name: Effects Nodes
    children:
    - OperationEffect
    - PitchShifter
    - RhinoGuitarProcessor
  
  - name: Modulation Effect Nodes
    children:
    - Chorus
    - Flanger
    - Phaser

  - name: Envelopes
    children:
    - AmplitudeEnvelope 
    - Tremolo

  - name: Filter Nodes
    children:
    - AutoWah
    - BandPassButterworthFilter
    - BandPassFilter
    - BandRejectButterworthFilter
    - CombFilterReverb
    - DCBlock
    - EqualizerFilter
    - FormantFilter
    - HighPassButterworthFilter
    - HighPassFilter
    - HighShelfFilter
    - HighShelfParametricEqualizerFilter
    - KorgLowPassFilter
    - LowPassButterworthFilter
    - LowPassFilter
    - LowShelfFilter
    - LowShelfParametricEqualizerFilter
    - ModalResonanceFilter
    - MoogLadder
    - ParametricEQ
    - PeakingParametricEqualizerFilter
    - ResonantFilter
    - RolandTB303Filter
    - StringResonator
    - ThreePoleLowpassFilter
    - ToneFilter
    - ToneComplementFilter

  - name: Reverb Nodes
    children:
    - ChowningReverb
    - CostelloReverb
    - Convolution
    - FlatFrequencyResponseReverb
    - Reverb
    - Reverb2
    - ZitaReverb

  - name: Noise Generator Nodes
    children:
    - BrownianNoise
    - PinkNoise
    - WhiteNoise

  - name: Oscillator Nodes
    children:
    - FMOscillator
    - MorphingOscillator
    - Oscillator
    - PhaseDistortionOscillator
    - PWMOscillator
    - Synth
    - SynthAudioUnit

  - name: Physical Models
    children:
    - Clarinet
    - Drip
    - Flute
    - MandolinString
    - MetalBar
    - PluckedString
    - RhodesPianoKey
    - Shaker
    - ShakerType
    - SynthKick
    - SynthSnare
    - TubularBells
    - VocalTract

  - name: Mixing Nodes
    children:
    - AutoPanner
    - Balancer
    - DryWetMixer
    - Fader
    - Mixer
    - Panner
    - StereoFieldLimiter

  - name: Playback Nodes
    children:

    - AppleSampler
    - AudioPlayer
    - PhaseLockedVocoder
    - PresetBuilder
    - Sampler
    - SamplerAudioUnit
    - SampleTriggerMode
    - SpeechSynthesizer
    - TimePitch
    - VariSpeed

  - name: Operations
    children:
    - ComputedParameter
    - Numeric
    - Operation
    - OperationParameter
    - Parameter
    - StereoOperation

  - name: Operation Math
    children:
    - abs(_:)
    - ceil(_:)
    - floor(_:)
    - fract(_:)
    - log(_:)
    - log10(_:)
    - max(_:_:)
    - min(_:_:)
    - mixer(_:_:balance:)
    - round(_:)
    - "*(_:_:)"
    - "+(_:_:)"
    - "-(_:_:)"
    - "-(_:)"
    - "/(_:_:)"

  - name: Plotting Tools
    children:
    - FloatChannelData
    - NodeFFTPlot
    - NodeOutputPlot
    - Waveform
    - WaveformDataRequest
    - WaveformLayer

  - name: Taps
    children:
    - AmplitudeTap
    - FFTTap
    - PitchTap
    - RawDataTap
    - TapNode

  - name: UI Elements
    children:
    - ADSRCallback
    - ADSRView
    - CrossPlatformColor
    - KeyboardView
    - KeyboardDelegate
    - MultitouchGestureRecognizer
    - MultitouchGestureRecognizerDelegate
    - PlaygroundLoop
    - Stylist
    - TableView
    - Theme

  - name: Math Approximation
    children:
    - ~!=(_:_:)
    - ~<(_:_:)
    - ~<=(_:_:)
    - ~==(_:_:)
    - ~>(_:_:)
    - ~>=(_:_:)

  - name: Apple Audio Extensions
    children:
    - AUParameter
    - AUParameterTree
    - AUValue
    - AudioComponentDescription
    - AudioUnit
    - AudioUnitParameterOptions
    - AVAudioEngine
    - AVAudioFile
    - AVAudioNode
    - AVAudioPCMBuffer
    - AVAudioSequencer
    - AVAudioSession
    - AVAudioTime

  - name: Music Notation
    children:
    - BPM
    - BPMType
    - TimeSignature

  - name: Type Extensions
    children:
    - Array
    - Bool
    - CGRect
    - ClosedRange
    - Dictionary
    - Double
    - Int
    - Notification
    - RangeReplaceableCollection
    - Set
    - String
    - UInt8







