module: AudioKit
author: Aurelius Prochazka
author_url: http://audiokit.io/
github_url: https://github.com/AudioKit/AudioKit
min_acl: public
readme: ../README.md
#swift_version: 3.0


custom_categories:
  - name: AudioKit Core
    children:
    - AudioEngine
    - AudioUnitBase
    - AudioUnitContainer
    - CallbackInstrument
    - Device
    - NodeParameter
    - NodeRecorder
    - Settings
    - Table
    - TableType

  - name: MIDI
    children:
    - BluetoothMIDIButton
    - MIDI
    - MIDICallback
    - MIDICallbackInstrument
    - MIDIClockListener
    - MIDIControl
    - MIDIEvent
    - MIDIFile
    - MIDIFileChunkEvent
    - MIDIFileTrack
    - MIDIFileTrackNoteMap
    - MIDIHelper
    - MIDIInstrument
    - MIDIListener
    - MIDIMonoPolyListener
    - MIDINode
    - MIDINoteData
    - MIDINoteDuration
    - MIDIOMNIListener
    - MIDIPlayer
    - MIDISampler
    - MIDIStatus
    - MIDIStatusType
    - MIDISystemCommand
    - MIDISystemCommandType
    - MIDISystemRealTimeListener
    - MIDITempoListener
    - MIDITransformer
    - MIDIFileTrackChunk
    - MIDIPacket
    - MIDIPacketList
    - MIDIProgramChangeEvent
    - MIDITimeFormat
    - MIDITimeout
    - MIDITrackView

  - name: Sequencing
    children:
    - AppleSequencer
    - Duration
    - MusicTrackManager
    - Sequencer
    - SequencerTrack

  - name: Tuning
    children:
    - TuningTable
    - TuningTableBase
    - TuningTableDelta12ET
    - TuningTableETNN

  - name: Utilities
    children:
    - CheckError(_:)
    - ExceptionCatcher(_:)
    - FormatConverter
    - fourCC(_:)
    - Log

  - name: Nodes
    children:
    - Node
    - Polyphonic
    - PolyphonicNode
    - Toggleable
    - OperationGenerator

  - name: Delay Nodes
    children:
    - Delay
    - StereoDelay
    - VariableDelay

  - name: Distortion Nodes
    children:
    - BitCrusher
    - Clipper
    - Decimator
    - DiodeClipper
    - Distortion
    - RingModulator
    - TanhDistortion

  - name: Dynamics Nodes
    children:
    - Compressor
    - DynamicsProcessor
    - DynamicRangeCompressor
    - DynaRageCompressor
    - Expander
    - PeakLimiter

  - name: Effects Nodes
    children:
    - OperationEffect
    - PitchShifter
    - RhinoGuitarProcessor
  
  - name: Modulation Effect Nodes
    children:
    - Chorus
    - Flanger
    - Phaser

  - name: Envelopes
    children:
    - AmplitudeEnvelope 
    - Tremolo

  - name: Filter Nodes
    children:
    - AutoWah
    - BandPassButterworthFilter
    - BandPassFilter
    - BandRejectButterworthFilter
    - CombFilterReverb
    - DCBlock
    - EqualizerFilter
    - FormantFilter
    - HighPassButterworthFilter
    - HighPassFilter
    - HighShelfFilter
    - HighShelfParametricEqualizerFilter
    - KorgLowPassFilter
    - LowPassButterworthFilter
    - LowPassFilter
    - LowShelfFilter
    - LowShelfParametricEqualizerFilter
    - ModalResonanceFilter
    - MoogLadder
    - ParametricEQ
    - PeakingParametricEqualizerFilter
    - ResonantFilter
    - RolandTB303Filter
    - StringResonator
    - ThreePoleLowpassFilter
    - ToneFilter
    - ToneComplementFilter

  - name: Reverb Nodes
    children:
    - ChowningReverb
    - CostelloReverb
    - Convolution
    - FlatFrequencyResponseReverb
    - Reverb
    - Reverb2
    - ZitaReverb

  - name: Noise Generator Nodes
    children:
    - BrownianNoise
    - PinkNoise
    - WhiteNoise

  - name: Oscillator Nodes
    children:
    - FMOscillator
    - MorphingOscillator
    - Oscillator
    - PhaseDistortionOscillator
    - PWMOscillator
    - Synth
    - SynthAudioUnit

  - name: Physical Models
    children:
    - Clarinet
    - Drip
    - Flute
    - MandolinString
    - MetalBar
    - PluckedString
    - RhodesPianoKey
    - Shaker
    - ShakerType
    - SynthKick
    - SynthSnare
    - TubularBells
    - VocalTract

  - name: Mixing Nodes
    children:
    - AutoPanner
    - Balancer
    - DryWetMixer
    - Fader
    - Mixer
    - Panner
    - StereoFieldLimiter

  - name: Playback Nodes
    children:

    - AppleSampler
    - AudioPlayer
    - PhaseLockedVocoder
    - PresetBuilder
    - Sampler
    - SamplerAudioUnit
    - SpeechSynthesizer
    - TimePitch
    - VariSpeed

  - name: Operations
    children:
    - Parameter
    - ComputedParameter
    - Operation
    - StereoOperation
    - Numeric

  - name: Math
    children:
    - abs(_:)
    - ceil(_:)
    - floor(_:)
    - fract(_:)
    - log(_:)
    - log10(_:)
    - max(_:_:)
    - min(_:_:)
    - mixer(_:_:balance:)
    - round(_:)
    - "*(_:_:)"
    - "+(_:_:)"
    - "-(_:_:)"
    - "-(_:)"
    - "/(_:_:)"

  - name: Random Number Generators
    children:
    - random(_:)

  - name: Plotting Tools
    children:
    - NodeFFTPlot
    - NodeOutputPlot

  - name: Taps
    children:
    - AmplitudeTap
    - FFTTap
    - PitchTap
    - RawDataTap
    - TapNode

  - name: UI Elements
    children:
    - ADSRView
    - CrossPlatformButton
    - KeyboardView
    - KeyboardDelegate
    - MultitouchGestureRecognizer
    - Stylist
    - TableView
    - Waveform
    - WaveformDataRequest
    - WaveformLayer

  - name: Apple Extensions
    children:
    - AVAudioEngine
    - AVAudioFile
    - AVAudioNode
    - AVAudioPCMBuffer
    - AVAudioTime
    - AudioComponentDescription
    - AudioUnit
