//
//  AKPeakingParametricEqualizerFilterAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

#ifndef AKPeakingParametricEqualizerFilterAudioUnit_h
#define AKPeakingParametricEqualizerFilterAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKPeakingParametricEqualizerFilterAudioUnit : AUAudioUnit
@end

#endif /* AKPeakingParametricEqualizerFilterAudioUnit_h */
