//
//  clip.swift
//  AudioKit For iOS
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright © 2015 AudioKit. All rights reserved.
//

import Foundation

extension AKParameter {

    /** clip: Applies clip-limiting to a signal - Clips a signal to a predefined limit, in a "soft" manner.
     - Parameter limit: Threshold / limiting value. (Default: 1.0, Minimum: 0.0, Maximum: 1.0)
     */
    public mutating func clip(limit limit: AKParameter = 1.0.ak) {
        self = self.clipped(limit: limit)
    }
    
    /** clipped: Applies clip-limiting to a signal - Clips a signal to a predefined limit, in a "soft" manner.
     - returns: AKParameter
     - Parameter limit: Threshold / limiting value. (Default: 1.0, Minimum: 0.0, Maximum: 1.0)
     */
    public  func clipped(limit limit: AKParameter = 1.0.ak) -> AKParameter {
        return AKParameter("\(self)\(limit)clip")
    }
}
