//
//  AKAUVarispeed.swift
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

import AVFoundation

/** AudioKit version of Apple's Varispeed Audio Unit */
public class AKAUVarispeed: AKOperation {
    
    private let cd = AudioComponentDescription(
        componentType: OSType(kAudioUnitType_Effect),
        componentSubType: OSType(kAudioUnitSubType_Varispeed),
        componentManufacturer: OSType(kAudioUnitManufacturer_Apple),
        componentFlags: 0,
        componentFlagsMask: 0)
    
    private var internalEffect = AVAudioUnitEffect()
    private var internalAU = AudioUnit()
    
    /** Playback Rate (Rate) ranges from 0.25 to 4.0 (Default: 1.0) */
    public var playbackRate: Float = 1.0 {
        didSet {
            if playbackRate < 0.25 {
                playbackRate = 0.25
            }
            if playbackRate > 4.0 {
                playbackRate = 4.0
            }
            AudioUnitSetParameter(internalAU, kVarispeedParam_PlaybackRate, kAudioUnitScope_Global, 0, playbackRate, 0)
        }
    }
    
    /** Playback Cents (Cents) ranges from -2400 to 2400 (Default: 0.0) */
    public var playbackCents: Float = 0.0 {
        didSet {
            if playbackCents < -2400 {
                playbackCents = -2400
            }
            if playbackCents > 2400 {
                playbackCents = 2400
            }
            AudioUnitSetParameter(internalAU, kVarispeedParam_PlaybackCents, kAudioUnitScope_Global, 0, playbackCents, 0)
        }
    }
    
    /** Initialize the varispeed operation */
    public init(
        _ input: AKOperation,
        playbackRate: Float = 1.0,
        playbackCents: Float = 0.0)
    {
        self.playbackRate = playbackRate
        self.playbackCents = playbackCents
        super.init()
        
        internalEffect = AVAudioUnitEffect(audioComponentDescription: cd)
        output = internalEffect
        AKManager.sharedInstance.engine.attachNode(internalEffect)
        AKManager.sharedInstance.engine.connect(input.output!, to: internalEffect, format: nil)
        internalAU = internalEffect.audioUnit
    }
}