//
//  AKDelay.swift
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

import AVFoundation

/** Add a delay to an incoming signal with optional feedback. */
public class AKDelay: AKOperation {

    // MARK: - Properties

    /** The underlying AudioUnit */
    private var internalAU: AKDelayAudioUnit?

    /** A generic parameter observer token */
    private var token: AUParameterObserverToken?

    /** Feedback amount. Should be a value between 0-1. */
    var feedbackParameter:  AUParameter?

    /** Feedback amount. Should be a value between 0-1. */
    public var feedback: Float = 0.0 {
        didSet {
            feedbackParameter?.setValue(feedback, originator: token!)
        }
    }

    // MARK: - Initializers

    /** Initialize this delay operation */
    public init(_ input: AKOperation) {
        super.init()

        var description = AudioComponentDescription()
        description.componentType         = kAudioUnitType_Effect
        description.componentSubType      = 0x646c6179 /*'dlay'*/
        description.componentManufacturer = 0x41754b74 /*'AuKt'*/
        description.componentFlags        = 0
        description.componentFlagsMask    = 0

        AUAudioUnit.registerSubclass(
            AKDelayAudioUnit.self,
            asComponentDescription: description,
            name: "Local AKDelay",
            version: UInt32.max)

        AVAudioUnit.instantiateWithComponentDescription(description, options: []) {
            avAudioUnit, error in

            guard let avAudioUnitEffect = avAudioUnit else { return }

            self.output = avAudioUnitEffect
            self.internalAU = avAudioUnitEffect.AUAudioUnit as? AKDelayAudioUnit
            AKManager.sharedInstance.engine.attachNode(self.output!)
            AKManager.sharedInstance.engine.connect(input.output!, to: self.output!, format: nil)
        }

        guard let tree = internalAU?.parameterTree else { return }

        feedbackParameter  = tree.valueForKey("feedback")  as? AUParameter

        token = tree.tokenByAddingParameterObserver {
            address, value in

            dispatch_async(dispatch_get_main_queue()) {
                if address == self.feedbackParameter!.address {
                    self.feedback = value
                }
            }
        }

    }
}
