//
//  AKResonantFilter.swift
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka on 9/9/15.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

import Foundation

/** A second-order resonant filter

{"A second-order resonant filter.  NOTE"=>"The output appears to be very hot, so take caution when using this module."}
*/
@objc class AKResonantFilter : AKParameter {

    // MARK: - Properties

    private var reson = UnsafeMutablePointer<sp_reson>.alloc(1)
    private var input = AKParameter()


    /** Center frequency of the filter, or frequency position of the peak response. [Default Value: 1000] */
    var centerFrequency: AKParameter = akp(1000) {
        didSet { centerFrequency.bind(&reson.memory.cutoff) }
    }

    /** Bandwidth of the filter (the Hz difference between the upper and lower half-power points). [Default Value: 10] */
    var bandwidth: AKParameter = akp(10) {
        didSet { bandwidth.bind(&reson.memory.bw) }
    }


    // MARK: - Initializers

    /** Instantiates the filter with default values */
    init(input sourceInput: AKParameter)

    {
        super.init()
        input = sourceInput
        setup()
        bindAll()
    }

    /**
    Instantiates the filter with all values

    :param: input Input audio signal. 
    :param: centerFrequency Center frequency of the filter, or frequency position of the peak response. [Default Value: 1000]
    :param: bandwidth Bandwidth of the filter (the Hz difference between the upper and lower half-power points). [Default Value: 10]
    */
    convenience init(
        input           sourceInput: AKParameter,
        centerFrequency cutoffInput: AKParameter,
        bandwidth       bwInput:     AKParameter)
    {
        self.init(input: sourceInput)

        centerFrequency = cutoffInput
        bandwidth       = bwInput

        bindAll()
    }

    // MARK: - Internals

    /** Bind every property to the internal filter */
    internal func bindAll() {
        centerFrequency.bind(&reson.memory.cutoff)
        bandwidth      .bind(&reson.memory.bw)
    }

    /** Internal set up function */
    internal func setup() {
        sp_reson_create(&reson)
        sp_reson_init(AKManager.sharedManager.data, reson)
    }

    /** Computation of the next value */
    override func compute() -> Float {
        sp_reson_compute(AKManager.sharedManager.data, reson, &(input.value), &value);
        pointer.memory = value
        return value
    }

    /** Release of memory */
    override func teardown() {
        sp_reson_destroy(&reson)
    }
}
