//
//  sineWave.swift
//  AudioKit For iOS
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright © 2015 AudioKit. All rights reserved.
//

import Foundation

extension AKParameter {

    /** sineWave: Sine wave oscillator - 
     - returns: AKParameter
     - Parameter frequency: Frequency in cycles per second (Default: 440)
     - Parameter amplitude: Amplitude of the output (Default: 1)
     */
    public static func sineWave(
        frequency frequency: AKParameter = 440.ak,
        amplitude: AKParameter = 1.ak
        ) -> AKParameter {
            return AKParameter("\(frequency)\(amplitude)sine")
    }
}

// Global Helper function

/** sineWave: Sine wave oscillator -
 - returns: AKParameter
 - Parameter frequency: Frequency in cycles per second (Default: 440)
 - Parameter amplitude: Amplitude of the output (Default: 1)
 */
public func sineWave(
    frequency frequency: AKParameter = 440.ak,
    amplitude: AKParameter = 1.ak
    ) -> AKParameter {
        return AKParameter.sineWave(frequency: frequency, amplitude: amplitude)
}