//
//  AKBalanceAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

#ifndef AKBalanceAudioUnit_h
#define AKBalanceAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKBalanceAudioUnit : AUAudioUnit
@end

#endif /* AKBalanceAudioUnit_h */
