// Copyright AudioKit. All Rights Reserved. Revision History at http://github.com/AudioKit/AudioKit/
// This file was auto-autogenerated by scripts and templates at http://github.com/AudioKit/AudioKitDevTools/

import AVFoundation
import CAudioKit

/// AudioKit version of Apple's ParametricEQ Audio Unit
///
open class ParametricEQ: Node, Toggleable {

    fileprivate let effectAU = AVAudioUnitEffect(
    audioComponentDescription:
    AudioComponentDescription(appleEffect: kAudioUnitSubType_ParametricEQ))

    /// Specification details for centerFreq
    public static let centerFreqDef = NodeParameterDef(
        identifier: "centerFreq",
        name: "Center Freq",
        address: 0,
        range: 20 ... 22050,
        unit: .hertz,
        flags: .default)

    /// Center Freq (Hertz) ranges from 20 to 22050 (Default: 2000)
    @Parameter(centerFreqDef) public var centerFreq: AUValue

    /// Specification details for q
    public static let qDef = NodeParameterDef(
        identifier: "q",
        name: "Q",
        address: 1,
        range: 0.1 ... 20,
        unit: .hertz,
        flags: .default)

    /// Q (Hertz) ranges from 0.1 to 20 (Default: 1.0)
    @Parameter(qDef) public var q: AUValue

    /// Specification details for gain
    public static let gainDef = NodeParameterDef(
        identifier: "gain",
        name: "Gain",
        address: 2,
        range: -20 ... 20,
        unit: .decibels,
        flags: .default)

    /// Gain (decibels) ranges from -20 to 20 (Default: 0)
    @Parameter(gainDef) public var gain: AUValue

    /// Tells whether the node is processing (ie. started, playing, or active)
    public var isStarted = true

    /// Initialize the parametric eq node
    ///
    /// - parameter input: Input node to process
    /// - parameter centerFreq: Center Freq (Hertz) ranges from 20 to 22050 (Default: 2000)
    /// - parameter q: Q (Hertz) ranges from 0.1 to 20 (Default: 1.0)
    /// - parameter gain: Gain (decibels) ranges from -20 to 20 (Default: 0)
    ///
    public init(
        _ input: Node,
        centerFreq: AUValue = 2000,
        q: AUValue = 1.0,
        gain: AUValue = 0) {
        super.init(avAudioNode: effectAU)
        connections.append(input)

        self.$centerFreq.associate(with: effectAU)
        self.$q.associate(with: effectAU)
        self.$gain.associate(with: effectAU)

        self.centerFreq = centerFreq
        self.q = q
        self.gain = gain
    }

    /// Function to start, play, or activate the node, all do the same thing
    public func start() {
        effectAU.bypass = false
        isStarted = true
    }

    /// Function to stop or bypass the node, both are equivalent
    public func stop() {
        effectAU.bypass = true
        isStarted = false
    }
}
