//
//  delay.swift
//  AudioKit For iOS
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright © 2015 AudioKit. All rights reserved.
//

import Foundation

extension AKOperation {

    /** Simple audio delay - Add a delay to an incoming signal with optional feedback.

     - parameter feedback: Feedback amount. (Default: 0, Minimum: 0, Maximum: 1)
     - parameter delayTime: Delay time, in seconds. (Default: 1, Minimum: 0, Maximum: 10)
     */
    public mutating func delay(time time: Float = 1, feedback: AKParameter = 0) {
        self = self.delayed(time: time, feedback: feedback)
    }

    /** Simple audio delay - Add a delay to an incoming signal with optional feedback.

     - returns: AKOperation
     - parameter feedback: Feedback amount. (Default: 0, Minimum: 0, Maximum: 1)
     - parameter delayTime: Delay time, in seconds. (Default: 1, Minimum: 0, Maximum: 10)
     */
    public func delayed(
        time time: Float = 1,
        feedback: AKParameter = 0
        ) -> AKOperation {
            return AKOperation("\(self) \(feedback) \(time) delay ")
    }
}
