module: AudioKit
author: Aurelius Prochazka
author_url: http://audiokit.io/
github_url: https://github.com/audiokit/AudioKit
min_acl: public
readme: ../README.md
#swift_version: 3.0


custom_categories:
  - name: AudioKit Core
    children:
    - AudioKit
    - AKAudioFile
    - AKComponent
    - AKCustomUgen
    - AKDevice
    - AKInput
    - AKLog(fullname:file:line:_:)
    - AKMicrophoneTracker
    - AKNodeRecorder
    - AKOutput
    - AKPeriodicFunction
    - AKSettings
    - AKTable
    - AKTableType
    - AKTester
    - AKTiming
    - AKTry(_:)
    - AKTuningTable
    - CheckError(_:)
    - fourCC(_:)
    - ">>>(_:_:)"

  - name: MIDI
    children:
    - AKMIDI
    - AKMIDICallback
    - AKMIDIControl
    - AKMIDIEvent
    - AKMIDIInstrument
    - AKMIDIListener
    - AKMIDINode
    - AKMIDISampler
    - AKMIDIStatus
    - AKMIDISystemCommand
    - AKMIDITransformer
    - AKRawMIDIPacket
    - MIDIPacket
    - MIDIPacketList
    - AKBluetoothMIDIButton
    - AKCallbackInstrument

  - name: Sequencer
    children:
    - AKSequencer
    - AKDuration
    - AKMusicTrack

  - name: Nodes
    children:
    - AKNode
    - AKPolyphonic
    - AKPolyphonicNode
    - AKToggleable
    - AKOperationGenerator

  - name: Analysis Nodes
    children:
    - AKAmplitudeTracker
    - AKFrequencyTracker

  - name: Delay Nodes
    children:
    - AKDelay
    - AKVariableDelay
    - AKVariableDelayAudioUnit

  - name: Distortion Nodes
    children:
    - AKBitCrusher
    - AKBitCrusherAudioUnit
    - AKClipper
    - AKClipperAudioUnit
    - AKDecimator
    - AKDistortion
    - AKRingModulator
    - AKTanhDistortion
    - AKTanhDistortionAudioUnit

  - name: Dynamics Nodes
    children:
    - AKCompressor
    - AKDynamicsProcessor
    - AKDynamicRangeCompressor
    - AKDynaRageCompressor
    - AKDynamicRangeCompressorAudioUnit
    - AKExpander
    - AKPeakLimiter

  - name: Effects Nodes
    children:
    - AKOperationEffect
    - AKPitchShifter
    - AKPitchShifterAudioUnit
    - AKRhinoGuitarProcessor
  
  - name: Modulation Effect Nodes
    children:
    - AKChorus
    - AKChorusAudioUnit
    - AKFlanger
    - AKFlangerAudioUnit
    - AKPhaser
    - AKPhaserAudioUnit

  - name: Envelopes
    children:
    - AKAmplitudeEnvelope 
    - AKAmplitudeEnvelopeAudioUnit
    - AKTremolo
    - AKTremoloAudioUnit

  - name: Filter Nodes
    children:
    - AKAutoWah
    - AKAutoWahAudioUnit
    - AKBandPassButterworthFilter
    - AKBandPassButterworthFilterAudioUnit
    - AKBandRejectButterworthFilter
    - AKBandRejectButterworthFilterAudioUnit
    - AKCombFilterReverb
    - AKCombFilterReverbAudioUnit
    - AKDCBlock
    - AKDCBlockAudioUnit
    - AKEqualizerFilter
    - AKEqualizerFilterAudioUnit
    - AKFormantFilter
    - AKFormantFilterAudioUnit
    - AKHighPassButterworthFilter
    - AKHighPassButterworthFilterAudioUnit
    - AKHighPassFilter
    - AKHighShelfFilter
    - AKHighShelfParametricEqualizerFilter
    - AKHighShelfParametricEqualizerFilterAudioUnit
    - AKKorgLowPassFilter
    - AKKorgLowPassFilterAudioUnit
    - AKLowPassButterworthFilter
    - AKLowPassButterworthFilterAudioUnit
    - AKLowPassFilter
    - AKLowShelfFilter
    - AKLowShelfParametricEqualizerFilter
    - AKLowShelfParametricEqualizerFilterAudioUnit
    - AKModalResonanceFilter
    - AKModalResonanceFilterAudioUnit
    - AKMoogLadder
    - AKMoogLadderAudioUnit
    - AKPeakingParametricEqualizerFilter
    - AKPeakingParametricEqualizerFilterAudioUnit
    - AKResonantFilter
    - AKResonantFilterAudioUnit
    - AKRolandTB303Filter
    - AKRolandTB303FilterAudioUnit
    - AKStringResonator
    - AKStringResonatorAudioUnit
    - AKThreePoleLowpassFilter
    - AKThreePoleLowpassFilterAudioUnit
    - AKToneFilter
    - AKToneFilterAudioUnit
    - AKToneComplementFilter
    - AKToneComplementFilterAudioUnit

  - name: Reverb Nodes
    children:
    - AKChowningReverb
    - AKChowningReverbAudioUnit
    - AKCostelloReverb
    - AKCostelloReverbAudioUnit
    - AKConvolution
    - AKFlatFrequencyResponseReverb
    - AKFlatFrequencyResponseReverbAudioUnit
    - AKReverb
    - AKReverb2
    - AKZitaReverb
    - AKZitaReverbAudioUnit

  - name: Noise Generator Nodes
    children:
    - AKBrownianNoise
    - AKBrownianNoiseAudioUnit
    - AKPinkNoise
    - AKPinkNoiseAudioUnit
    - AKWhiteNoise
    - AKWhiteNoiseAudioUnit

  - name: Oscillator Nodes
    children:
    - AKFMOscillator
    - AKFMOscillatorAudioUnit
    - AKFMOscillatorBank
    - AKMorphingOscillator
    - AKMorphingOscillatorAudioUnit
    - AKMorphingOscillatorBank
    - AKOscillator
    - AKOscillatorAudioUnit
    - AKOscillatorBank
    - AKPhaseDistortionOscillator
    - AKPhaseDistortionOscillatorAudioUnit
    - AKPhaseDistortionOscillatorBank
    - AKPWMOscillator
    - AKPWMOscillatorAudioUnit
    - AKPWMOscillatorBank

  - name: Physical Models
    children:
    - AKClarinet
    - AKClarinetAudioUnit
    - AKDrip
    - AKDripAudioUnit
    - AKFlute
    - AKFluteAudioUnit
    - AKMandolin
    - AKMetalBar
    - AKMetalBarAudioUnit
    - AKPluckedString
    - AKPluckedStringAudioUnit
    - AKRhodesPiano
    - AKShaker
    - AKShakerType
    - AKSynthKick
    - AKSynthSnare
    - AKTubularBells
    - AKVocalTract
    - AKVocalTractAudioUnit

  - name: Input Node
    children:
    - AKMicrophone
    - AKStereoInput

  - name: Mixing Nodes
    children:
    - AK3DPanner
    - AKBalancer
    - AKBooster
    - AKBoosterAudioUnit
    - AKDryWetMixer
    - AKMixer
    - AKPanner
    - AKStereoFieldLimiter

  - name: Playback Nodes
    children:

    - AKAppleSampler
    - AKClip
    - AKClipMerger
    - AKClipPlayer
    - AKClipRecorder
    - AKFileClip
    - AKFileClipSequence
    - AKMetronome
    - AKPhaseLockedVocoder
    - AKPlayer
    - AKRecordingResult
    - AKSampler
    - AKSamplePlayer
    - AKTimePitch
    - AKVariSpeed
    - ClipMergeDelegate
    - ClipMergerError
    - ClipRecordingError
    - FileClip
    - Sample
    - SampleTriggerModer

  - name: Operations
    children:
    - AKParameter
    - AKComputedParameter
    - AKOperation
    - AKStereoOperation
    - Numeric

  - name: Math
    children:
    - abs(_:)
    - ceil(_:)
    - floor(_:)
    - fract(_:)
    - log(_:)
    - log10(_:)
    - max(_:_:)
    - min(_:_:)
    - mixer(_:_:balance:)
    - round(_:)
    - "*(_:_:)"
    - "+(_:_:)"
    - "-(_:_:)"
    - "-(_:)"
    - "/(_:_:)"

  - name: Random Number Generators
    children:
    - random(_:_:)

  - name: Plotting Tools
    children:
    - AKRollingOutputPlot
    - AKNodeFFTPlot
    - AKNodeOutputPlot
    - AKOutputWaveformPlot

  - name: Taps
    children:
    - AKAmplitudeTap
    - AKFFTTap

  - name: UI Elements
    children:
    - AKADSRView
    - AKButton
    - AKBypassButton
    - AKKeyboardView
    - AKKeyboardDelegate
    - AKPlaygroundLoop
    - AKPlaygroundView
    - AKPresetLoaderView
    - AKPropertySlider
    - AKResourcesAudioFileLoaderView
    - AKStepper
    - AKTelephoneView
    - MultitouchGestureRecognizer

  - name: Apple Extensions
    children:
    - AVAudioCommonFormat
    - AVAudioEngine
    - AVAudioFile
    - AVAudioNode
    - AVAudioPCMBuffer
    - AVAudioTime
    - AVAudioUnit
    - AudioComponentDescription
    - AudioUnit