module: AudioKit
author: Aurelius Prochazka
author_url: http://audiokit.io/
github_url: https://github.com/audiokit/AudioKit
min_acl: public
readme: ../README.md
#swift_version: 3.0


custom_categories:
  - name: AudioKit Core
    children:
    - AudioKit
    - AKAudioFile
    - AKCustomUgen
    - AKDevice
    - AKMicrophoneTracker
    - AKNodeRecorder
    - AKPeriodicFunction
    - AKSettings
    - AKTable
    - AKTableType
    - AKTester
    - AKTuningTable

  - name: MIDI
    children:
    - AKMIDI
    - AKMIDIEvent
    - AKMIDIControl
    - AKMIDIInstrument
    - AKMIDIListener
    - AKMIDINode
    - AKMIDISampler
    - AKMIDIStatus
    - AKMIDISystemCommand
    - MIDIPacket
    - MIDIPacketList
    - AKBluetoothMIDIButton
    - AKCallbackInstrument

  - name: Sequencer
    children:
    - AKSequencer
    - AKDuration
    - AKMusicTrack

  - name: Nodes
    children:
    - AKNode
    - AKPolyphonic
    - AKPolyphonicNode
    - AKToggleable
    - AKOperationGenerator

  - name: Analysis Nodes
    children:
    - AKAmplitudeTracker
    - AKFrequencyTracker

  - name: Delay Nodes
    children:
    - AKDelay
    - AKVariableDelay

  - name: Distortion Nodes
    children:
    - AKBitCrusher
    - AKClipper
    - AKDecimator
    - AKDistortion
    - AKRingModulator
    - AKTanhDistortion

  - name: Dynamics Nodes
    children:
    - AKCompressor
    - AKDynamicsProcessor
    - AKDynamicRangeCompressor
    - AKExpander
    - AKPeakLimiter

  - name: Effects Nodes
    children:
    - AKOperationEffect
    - AKPhaser
    - AKPitchShifter

  - name: Envelopes
    children:
    - AKAmplitudeEnvelope
    - AKTremolo

  - name: Filter Nodes
    children:
    - AKAutoWah
    - AKBandPassButterworthFilter
    - AKBandRejectButterworthFilter
    - AKCombFilterReverb
    - AKDCBlock
    - AKEqualizerFilter
    - AKFormantFilter
    - AKHighPassButterworthFilter
    - AKHighPassFilter
    - AKHighShelfFilter
    - AKHighShelfParametricEqualizerFilter
    - AKKorgLowPassFilter
    - AKLowPassButterworthFilter
    - AKLowPassFilter
    - AKLowShelfFilter
    - AKLowShelfParametricEqualizerFilter
    - AKModalResonanceFilter
    - AKMoogLadder
    - AKPeakingParametricEqualizerFilter
    - AKResonantFilter
    - AKRolandTB303Filter
    - AKStringResonator
    - AKThreePoleLowpassFilter
    - AKToneFilter
    - AKToneComplementFilter

  - name: Reverb Nodes
    children:
    - AKChowningReverb
    - AKCostelloReverb
    - AKConvolution
    - AKFlatFrequencyResponseReverb
    - AKReverb
    - AKReverb2
    - AKZitaReverb

  - name: Noise Generator Nodes
    children:
    - AKBrownianNoise
    - AKPinkNoise
    - AKWhiteNoise

  - name: Oscillator Nodes
    children:
    - AKFMOscillator
    - AKFMOscillatorBank
    - AKMorphingOscillator
    - AKMorphingOscillatorBank
    - AKOscillator
    - AKOscillatorBank
    - AKPhaseDistortionOscillator
    - AKPhaseDistortionOscillatorBank
    - AKPWMOscillator
    - AKPWMOscillatorBank

  - name: Physical Models
    children:
    - AKClarinet
    - AKDrip
    - AKFlute
    - AKMandolin
    - AKMetalBar
    - AKPluckedString
    - AKRhodesPiano
    - AKShaker
    - AKSynthKick
    - AKSynthSnare
    - AKTubularBells
    - AKVocalTract

  - name: Input Node
    children:
    - AKMicrophone
    - AKStereoInput

  - name: Mixing Nodes
    children:
    - AK3DPanner
    - AKBalancer
    - AKBooster
    - AKDryWetMixer
    - AKMixer
    - AKPanner
    - AKStereoFieldLimiter

  - name: Playback Nodes
    children:
    - AKAudioPlayer
    - AKMetronome
    - AKPhaseLockedVocoder
    - AKSamplePlayer
    - AKSampler
    - AKTimePitch
    - AKVariSpeed

  - name: Operations
    children:
    - AKParameter
    - AKComputedParameter
    - AKOperation
    - AKStereoOperation
    - Numeric

  - name: Math
    children:
    - abs(_:)
    - ceil(_:)
    - floor(_:)
    - fract(_:)
    - log(_:)
    - log10(_:)
    - max(_:_:)
    - min(_:_:)
    - mixer(_:_:balance:)
    - round(_:)
    - "*(_:_:)"
    - "+(_:_:)"
    - "-(_:_:)"
    - "/(_:_:)"
    - "==(_:_:)"
    - "!=(_:_:)"
    - "<(_:_:)"
    - "<=(_:_:)"
    - ">(_:_:)"
    - ">=(_:_:)"
    - "%(_:_:)"
    - "+=(_:_:)"
    - "-=(_:_:)"

  - name: Random Number Generators
    children:
    - random(_:_:)

  - name: Plotting Tools
    children:
    - AKRollingOutputPlot
    - AKNodeFFTPlot
    - AKNodeOutputPlot
    - AKOutputWaveformPlot

  - name: Taps
    children:
    - AKAmplitudeTap
    - AKFFTTap

  - name: UI Elements
    children:
    - AKADSRView
    - AKButton
    - AKBypassButton
    - AKKeyboardView
    - AKKeyboardDelegate
    - AKPlaygroundLoop
    - AKPlaygroundView
    - AKPresetLoaderView
    - AKPropertySlider
    - AKResourcesAudioFileLoaderView
    - AKStepper
    - AKTelephoneView
    - MultitouchGestureRecognizer