//
//  periodicTrigger.swift
//  AudioKit For iOS
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright © 2015 AudioKit. All rights reserved.
//

import Foundation

extension AKOperation {

    /** Periodic Trigger - Produce a set of triggers spaced apart by time.

     - parameter period: Time between triggers (in seconds). This will update at the start of each trigger. (Default: 1)
     */
    public static func periodicTrigger(period: AKParameter = 1) -> AKOperation {
        return AKOperation("(\(period) dmetro)")
    }
}

/** Periodic Trigger - Produce a set of triggers spaced apart by time.

- returns: AKOperation
- parameter period: Time between triggers (in seconds). This will update at the start of each trigger. (Default: 1)
*/
public func periodicTrigger(period: AKParameter = 1) -> AKOperation {
    return AKOperation.periodicTrigger(period)
}