//
//  AKClipperAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

#ifndef AKClipperAudioUnit_h
#define AKClipperAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKClipperAudioUnit : AUAudioUnit
@end

#endif /* AKClipperAudioUnit_h */
