//
//  AKThreePoleLowpassFilterAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

#ifndef AKThreePoleLowpassFilterAudioUnit_h
#define AKThreePoleLowpassFilterAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKThreePoleLowpassFilterAudioUnit : AUAudioUnit
@end

#endif /* AKThreePoleLowpassFilterAudioUnit_h */
