//
//  AKCustomModifierAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2015 Aurelius Prochazka. All rights reserved.
//

#ifndef AKCustomModifierAudioUnit_h
#define AKCustomModifierAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKCustomModifierAudioUnit : AUAudioUnit
- (void)setSporth:(NSString *)sporth;
@end

#endif /* AKCustomModifierAudioUnit_h */
