# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AudioKitPlayground' do
  pod 'KZPlayground', '0.3.2'
end



