//
//  AKTanhDistortionAudioUnit.h
//  AudioKit
//
//  Autogenerated by scripts by Aurelius Prochazka. Do not edit directly.
//  Copyright (c) 2016 Aurelius Prochazka. All rights reserved.
//

#ifndef AKTanhDistortionAudioUnit_h
#define AKTanhDistortionAudioUnit_h

#import <AudioToolbox/AudioToolbox.h>

@interface AKTanhDistortionAudioUnit : AUAudioUnit
- (void)start;
- (void)stop;
- (BOOL)isPlaying;
@end

#endif /* AKTanhDistortionAudioUnit_h */
